ALTER TABLE sql_task
    ADD COLUMN sql_type VARCHAR(50) DEFAULT 'OTHER' COMMENT 'SQL 类型: SELECT / INSERT / UPDATE / DELETE / OTHER',
    ADD COLUMN status VARCHAR(20) DEFAULT 'DRAFT' COMMENT '任务状态: DRAFT / PUBLISHED';
